by_address <- function(d) {
  d %>% 
    group_by(Address)
}

by_address_and_chapter <- function(d) {
  d %>% 
    group_by(Address, Ordinance.Chapter)
}

summarize_by_address <- function(d) {
  d %>% 
    by_address() %>% 
    summary_basic() %>% 
    ungroup()
}

add_total_violations_column <- function(d) {
  e <- summarize_by_address(d) 
  left_join(d, e, by = 'Address')  
}

# assumes the total violations by address column 
# has already been added
plot_violations_for_address_frequency <- function(d) {
  d %>% 
    ggplot(aes(x = Violation.Count)) + geom_histogram(binwidth = 1) + 
    scale_x_continuous(limits = c(0,75)) + 
    labs(title = "Violations per Address") +
    xlab("Number of Violations at an Address") +
    ylab("Violation Count")
}

plot_median_days_open_by_group_violation_count <- function(d) {
  d %>% 
    ggplot(aes(Violation.Count, Median.Days.Open)) +    
    geom_bar(stat="identity") + 
    scale_x_continuous(limits = c(0,75)) + 
    labs(title="Median Days Open by # Violations Per Address (2009-2016)") + 
    xlab("# of Violations") + ylab("Median Days Open") +
    theme(axis.text.x  = element_text(angle=90, vjust=0.5, size=8))  
}

plot_mean_days_open_by_group_violation_count <- function(d) {
  d %>% 
    ggplot(aes(Violation.Count, Mean.Days.Open)) +    
    geom_bar(stat="identity") + 
    scale_x_continuous(limits = c(0,75)) + 
    labs(title="Mean Days Open by # Violations Per Address (2009-2016)") + 
    xlab("# of Violations") + ylab("Mean Days Open") +
    theme(axis.text.x  = element_text(angle=90, vjust=0.5, size=8))  
}

plot_group_count_showing_ordinances <- function(d) {
  d %>% 
    ggplot(aes(x = Violation.Count, y = n(), fill = Ordinance.Title)) + geom_histogram(binwidth = 1) + 
    scale_x_continuous(limits = c(0,75)) + 
    labs(title = "Violations per Address") +
    xlab("Number of Violations at an Address") +
    ylab("Violation Count")
}

plot_group_count_showing_chapters <- function(d) {
  d %>% 
    ggplot(aes(x = Violation.Count, fill = Ordinance.Chapter)) + geom_histogram(binwidth = 1) + 
    scale_x_continuous(limits = c(0,75)) + 
    labs(title = "Violations per Address") +
    xlab("Number of Violations at an Address") +
    ylab("Violation Count")
}

compute_cumulative_percent_violations_for_addresses <- function(d)  {
  t <- d %>% 
    summarize_by_address() %>% 
    group_by(Violation.Count) %>% 
    summarize(Address.Count = n())  %>% 
    mutate(Total.Violations = Violation.Count * Address.Count) %>% 
    arrange(desc(Violation.Count))
  c <- t %>% 
    select(2:3) %>% 
    cumsum()  
  
  t$Cum.Address.Count <- c$Address.Count
  t$Cum.Total.Violations <- c$Total.Violations
  
  t %>% 
    mutate(Cum.Percent.Address = round(Cum.Address.Count/sum(Address.Count), digits = 4)*100,
           Cum.Percent.Violations =  round(Cum.Total.Violations/sum(Total.Violations), digits = 4)*100) %>% 
    select(Violation.Count, Cum.Percent.Address, Cum.Percent.Violations)
}

plot_cumulative_percent_violations <- function(d) {
  d %>% 
    compute_cumulative_percent_violations_for_addresses() %>% 
    ggplot(aes(x=Cum.Percent.Address, y=Cum.Percent.Violations)) + 
    geom_line() +
    labs(title = "Violations Generated by Addresses") +
    xlab("Percent of  Addresses") +
    ylab("Percent of Violations")
}
